### PR TITLE
Add --no-auto-update

### PR DESCRIPTION
**Pull request by SuperQ**
**Description**
Add a flag to disable the auto-update. Useful to avoid trying to sync as a boot command.
* Fix up missing --no-color help text.

⚒️ Fixes  # 

**⚙️ Type of change**

- [x] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by Ornias1993** [comment]
Auto update isnt used unless -u or -U is set anyway.

**Comment by Ornias1993** [comment]
We’re currently planning to rework TrueTool completely so are not accepting PR’s anyway…

**Comment by SuperQ** [comment]
Weird, because reading the code, it does it no matter what.

**Comment by SuperQ** [comment]
```
# ./truetool.sh --kubeapi-enable
  _______               _____ _                _       
 |__   __|             / ____| |              | |      
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___ 
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |                
    | |_ __ _   _  ___| | ___   ___ | |                
    | | '__| | | |/ _ \ |/ _ \ / _ \| |                
    | | |  | |_| |  __/ | (_) | (_) | |                
    |_|_|   \__,_|\___|_|\___/ \___/|_|                
                                                       
                                                       
Checking for updates...
TrueTool requires update
script updated
restarting script after update...
Checking for updates...
script up-to-date

Enabling Kubernetes API
Kubernetes API already enabled
```

With my change:
```
# ./truetool.sh --kubeapi-enable --no-auto-update
  _______               _____ _                _       
 |__   __|             / ____| |              | |      
    | |_ __ _   _  ___| |    | |__   __ _ _ __| |_ ___ 
    | | '__| | | |/ _ \ |    | '_ \ / _` | '__| __/ __|
    | | |  | |_| |  __/ |____| | | | (_| | |  | |_\__ \
  __|_|_|   \__,_|\___|\_____|_| |_|\__,_|_|   \__|___/
 |__   __|         |__   __|        | |                
    | |_ __ _   _  ___| | ___   ___ | |                
    | | '__| | | |/ _ \ |/ _ \ / _ \| |                
    | | |  | |_| |  __/ | (_) | (_) | |                
    |_|_|   \__,_|\___|_|\___/ \___/|_|                
                                                       
                                                       
Enabling Kubernetes API
Kubernetes API already enabled
```

**Comment by Ornias1993** [comment]
Ahh you meant no auto-update of the script.
Well... this was a design decision.

We want to be 100% sure people are running the latest version all the time.

**Comment by SuperQ** [comment]
Alright, I'll just run with my fork permanently. I consider having forced auto-update, with no way to opt-out, a bad idea. (See also, why I refuse to use snap packages)

For example, the `--kubeapi-enable` needs to be run every boot, as the firewall rule is added every time by middlewared. So I need to have a post-init script configured to run it at startup. I don't want the script auto-updating, as root, in the middle of boot.

**Comment by Ornias1993** [comment]
"I don't want the script auto-updating, as root, in the middle of boot."
We never adviced anyone to be running this at boot. It should only be run after the boot sequence.

"I consider having forced auto-update, with no way to opt-out, a bad idea."
As I said: we're in the progress of a huge rework. So the PR closing is not a "no", but rather a "not now at least"

**Pull request closed without merging**
